namespace linq.data
{
    public enum EIngredient
    {
        TOMATOE, ONION, SALT, WATER, PEPPER, GARLIC, BROTH, PUMPKIN, CREAM, VEAL, BREAD_CRUMBS, FLOUR, LEMON, BUTTER, OIL, MILK, CHEESE, WINE, MUSHROOM, SHALLOT, PASTA, BACON, PARMESAN_CHEESE, EGG, EGG_YOLK, CHIVES, CELERY, CARROT 
    }
}